AWSTemplateFormatVersion: '2010-09-09'
Metadata: 
  License: Apache-2.0
  Description: 'AWS CloudFormation template for DataRep security'
Parameters: 
  EnvType: 
    Description: Environment type.
    Default: DEV
    Type: String
    AllowedValues: 
      - DEV
      - INT
      - PERF
      - PROD
  SecurityStack:
    Description: Stack from which to retrieve security values
    Type: String
Resources:
  DataRepEBSVol1:
    Type: AWS::EC2::Volume
    Properties:
      Size: 50
      AvailabilityZone: us-east-1a
      Encrypted: true
      KmsKeyId:
        'Fn::ImportValue': !Sub '${SecurityStack}-KmsKeyId'
