AWSTemplateFormatVersion: '2010-09-09'
Metadata: 
  License: Apache-2.0
  Description: 'AWS CloudFormation template for DataRep security'
Parameters: 
  EnvType: 
    Description: Environment type.
    Default: DEV
    Type: String
    AllowedValues: 
      - DEV
      - INT
      - PERF
      - PROD
Conditions: 
  CreateProdResources: !Equals [ !Ref EnvType, PROD ]
  LowerEnvironment:
    !Not [!Equals [!Ref EnvType, PROD]]
Resources:
  DataRepCFRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "cloudformation.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      Path: "/DataRep/"
      ManagedPolicyArns: 
      - !Ref DataRepIAMPolicy
  DataRepS3Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: ['sts:AssumeRole']
          Effect: Allow
          Principal:
            Service: [s3.amazonaws.com]
  DataRepIAMPolicy:
    Type: AWS::IAM::ManagedPolicy
    Condition: LowerEnvironment
    Properties:
      Description: "Managed IAM policy for DataRep"
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - 
          Effect: Allow
          Action:
          - cloudformation:*
          Resource:
            !Sub arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/DataRep-${EnvType}-*
        - 
          Effect: Allow
          Action:
          - ec2:CreateVolume
          Resource:
            !Sub arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:volume/*
  DataRepGroup:
    Type: AWS::IAM::Group
    Properties:
      Path: "/DataRep/"
      ManagedPolicyArns: 
      - !Ref DataRepIAMPolicy
  DataRepKMSKey: 
    Type: "AWS::KMS::Key"
    Properties: 
      Description: "A sample key"
      KeyPolicy: 
        Version: "2012-10-17"
        Id: "KMSKey-DataRep"
        Statement: 
          - 
            Sid: "Allow administration of the key"
            Effect: "Allow"
            Principal: 
              AWS: 
                !Sub "arn:aws:iam::${AWS::AccountId}:role/DEMO-IAMFull"
            Action: 
              - "kms:Create*"
              - "kms:Describe*"
              - "kms:Enable*"
              - "kms:List*"
              - "kms:Put*"
              - "kms:Update*"
              - "kms:Revoke*"
              - "kms:Disable*"
              - "kms:Get*"
              - "kms:Delete*"
              - "kms:ScheduleKeyDeletion"
              - "kms:CancelKeyDeletion"
            Resource: "*"
          - 
            Sid: "Allow use of the key"
            Effect: "Allow"
            Principal: 
              AWS: !GetAtt DataRepCFRole.Arn
            Action: 
              - "kms:Encrypt"
              - "kms:Decrypt"
              - "kms:ReEncrypt*"
              - "kms:GenerateDataKey*"
              - "kms:DescribeKey"
            Resource: "*"
Outputs:
  DataRepKmsKeyId:
    Description: ARN of the DataRep KMS key
    Value: !GetAtt DataRepKMSKey.Arn
    Export:
      Name: !Sub "${AWS::StackName}-KmsKeyId"
