AWSTemplateFormatVersion: '2010-09-09'
Metadata: 
  License: Apache-2.0
  Description: 'AWS CloudFormation template for DataRep security'
Parameters: 
  EnvType: 
    Description: Environment type.
    Default: DEV
    Type: String
    AllowedValues: 
      - DEV
      - INT
      - PERF
      - PROD
Conditions: 
  CreateProdResources: !Equals [ !Ref EnvType, PROD ]
  LowerEnvironment:
    !Not [!Equals [!Ref EnvType, PROD]]
Resources:
  DataRepCFRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "cloudformation.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      Path: "/DataRep/"
      ManagedPolicyArns: 
      - !Ref DataRepDevPolicy
  DataRepProdPolicy:
    Type: AWS::IAM::ManagedPolicy
    Condition: CreateProdResources
    Properties:
      Description: "Policy for DataRep Production"
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - cloudformation:CreateChangeSet
          - cloudformation:CreateStack
          - cloudformation:DescribeAccountLimits
          - cloudformation:DescribeChangeSet
          - cloudformation:DescribeStackEvents
          - cloudformation:DescribeStackResource
          - cloudformation:DescribeStackResources
          - cloudformation:DescribeStacks
          - cloudformation:GetStackPolicy
          - cloudformation:ListChangeSets
          - cloudformation:ListStackResources
          - cloudformation:ListStacks
          Resource:
            !Sub arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/DataRep-PROD-*
  DataRepDevPolicy:
    Type: AWS::IAM::ManagedPolicy
    Condition: LowerEnvironment
    Properties:
      Description: "Policy for DataRep Development"
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - cloudformation:*
          Resource:
            !Sub arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/DataRep-DEV-*
  DataRepDevGroup:
    Condition: LowerEnvironment
    Type: AWS::IAM::Group
    Properties:
      Path: "/DataRep/"
      ManagedPolicyArns: 
      - !Ref DataRepDevPolicy
  DataRepProdGroup:
    Condition: CreateProdResources
    Type: AWS::IAM::Group
    Properties:
      Path: "/DataRep/"
      ManagedPolicyArns: 
      - !Ref DataRepProdPolicy
  DataRepKMSKey: 
    Type: "AWS::KMS::Key"
    Properties: 
      Description: "A sample key"
      KeyPolicy: 
        Version: "2012-10-17"
        Id: "KMSKey-DataRep"
        Statement: 
          - 
            Sid: "Allow administration of the key"
            Effect: "Allow"
            Principal: 
              AWS: 
                !Sub "arn:aws:iam::${AccountId}:role/DEMO-IAMFull"
            Action: 
              - "kms:Create*"
              - "kms:Describe*"
              - "kms:Enable*"
              - "kms:List*"
              - "kms:Put*"
              - "kms:Update*"
              - "kms:Revoke*"
              - "kms:Disable*"
              - "kms:Get*"
              - "kms:Delete*"
              - "kms:ScheduleKeyDeletion"
              - "kms:CancelKeyDeletion"
            Resource: "*"
